<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WSAMZN-7ID4CD15" failures="1" tests="6" name="com.gapi.testCases.CreateNewUser" time="7.845" errors="0" timestamp="2023-04-04T15:40:47 UTC" skipped="2">
  <testcase classname="com.gapi.testCases.CreateNewUser" name="verifyCreateNewUser" time="0.388"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateNewUser" name="verifyCreateNewUser" time="0.494">
    <skipped/>
  </testcase> <!-- verifyCreateNewUser -->
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateNewUser" name="verifyCreateNewUser" time="2.322"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateNewUser" name="verifyCreateNewUser" time="0.502">
    <failure message="expected [201] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [400]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.gapi.testCases.CreateNewUser.verifyCreateNewUser(CreateNewUser.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCreateNewUser -->
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateNewUser" name="verifyCreateNewUser" time="0.748">
    <skipped/>
  </testcase> <!-- verifyCreateNewUser -->
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateNewUser" name="verifyCreateNewUser" time="3.391"/>
  <system-out/>
</testsuite> <!-- com.gapi.testCases.CreateNewUser -->
